package dev.dokimos.examples.conversation.goldens;

import static org.assertj.core.api.Assertions.assertThat;

import dev.dokimos.core.Assertions;
import dev.dokimos.core.Example;
import dev.dokimos.core.JudgeLM;
import dev.dokimos.core.conversation.ConversationSimulator;
import dev.dokimos.core.conversation.ConversationTrajectory;
import dev.dokimos.core.conversation.Message;
import dev.dokimos.core.conversation.SimulatedUser;
import dev.dokimos.core.evaluators.agents.TaskCompletionEvaluator;
import dev.dokimos.junit.DatasetSource;
import dev.dokimos.langchain4j.LangChain4jSupport;
import dev.langchain4j.model.openai.OpenAiChatModel;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.junit.jupiter.params.ParameterizedTest;

/**
 * Replays the goldens generated by {@link GenerateSupportGoldens} against the current
 * {@link SupportDesk}.
 *
 * <p>Each example carries the recorded transcript in {@code inputs["input"]} and the criterion the
 * conversation was supposed to meet in {@code metadata["expectedOutcome"]}. The recorded user turns
 * are pulled out of the transcript and replayed verbatim, the desk answers them again, and the judge
 * grades the conversation that comes back. A prompt or model change that stops the desk reaching the
 * outcome fails here.
 *
 * <p>Only the user side is replayed. The whole transcript holds the desk's own replies, so sending
 * it back as a prompt would hand the model the answer it is being graded on.
 *
 * <p>The user turns are recovered by splitting the rendered transcript on its {@code USER: },
 * {@code ASSISTANT: } and {@code SYSTEM: } line prefixes. That is good enough for a support desk, but
 * it is not a parser: a reply that itself begins a line with one of those prefixes would be read as a
 * new turn. Keep the recorded turns somewhere structured if your application can emit them.
 *
 * <p>This test is skipped by default. Run with:
 *
 * <pre>
 * RUN_EVAL_TESTS=true OPENAI_API_KEY='your-key' mvn test -pl dokimos-examples -Dtest=SupportGoldenReplayTest
 * </pre>
 */
@EnabledIfEnvironmentVariable(named = "RUN_EVAL_TESTS", matches = "true")
@EnabledIfEnvironmentVariable(named = "OPENAI_API_KEY", matches = ".+")
class SupportGoldenReplayTest {

    private static final List<String> ROLE_PREFIXES = List.of("USER: ", "ASSISTANT: ", "SYSTEM: ");

    private SupportDesk supportDesk;
    private TaskCompletionEvaluator outcomeReached;

    @BeforeEach
    void setup() {
        String apiKey = System.getenv("OPENAI_API_KEY");

        supportDesk = SupportDesk.withOpenAi(apiKey);

        JudgeLM judge = LangChain4jSupport.asJudge(OpenAiChatModel.builder()
                .apiKey(apiKey)
                .modelName(SupportDesk.MODEL_ID)
                .build());

        outcomeReached = TaskCompletionEvaluator.builder()
                .name("Expected Outcome")
                .judge(judge)
                .threshold(1.0)
                .build();
    }

    @ParameterizedTest
    @DatasetSource("classpath:datasets/support-goldens.json")
    void shouldReachTheExpectedOutcome(Example example) {
        String expectedOutcome = example.metadataAs("expectedOutcome", String.class);
        assertThat(expectedOutcome)
                .as("golden %s carries no expectedOutcome to grade against", example.datasetItemId())
                .isNotNull();

        List<String> userTurns = recordedUserTurns(example.input());
        assertThat(userTurns)
                .as("golden %s records no user turn to replay", example.datasetItemId())
                .isNotEmpty();

        ConversationTrajectory replay = ConversationSimulator.builder()
                .application(supportDesk)
                .simulatedUser(scriptOf(userTurns))
                .scenario(example.metadataAs("scenario", String.class))
                .maxTurns(userTurns.size())
                .build()
                .simulate();

        Assertions.assertEval(replay.toTestCase(List.of(), List.of(expectedOutcome)), outcomeReached);
    }

    private static SimulatedUser scriptOf(List<String> userTurns) {
        return trajectory -> {
            int index = trajectory.userMessages().size();
            return Message.user(index < userTurns.size() ? userTurns.get(index) : "");
        };
    }

    private static List<String> recordedUserTurns(String transcript) {
        List<String> turns = new ArrayList<>();
        StringBuilder current = null;
        for (String line : transcript.split("\n")) {
            if (startsATurn(line)) {
                if (current != null) {
                    turns.add(current.toString().strip());
                }
                current = line.startsWith("USER: ") ? new StringBuilder(line.substring("USER: ".length())) : null;
            } else if (current != null) {
                current.append("\n").append(line);
            }
        }
        if (current != null) {
            turns.add(current.toString().strip());
        }
        return turns;
    }

    private static boolean startsATurn(String line) {
        return ROLE_PREFIXES.stream().anyMatch(line::startsWith);
    }
}
