/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  AddItems201,
  AddItemsRequest,
  GetRunDetailsParams,
  RunDetails,
  UpdateRun200,
  UpdateRunRequest
} from '../generated.schemas';



  
  
  
export const addItems = (
    runId: string,
    addItemsRequest: AddItemsRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AddItems201>> => {
    return axios.default.post(
      `/api/v1/runs/${runId}/items`,
      addItemsRequest,options
    );
  }



export const getAddItemsMutationFetcher = (runId: string, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: AddItemsRequest }) => {
    return addItems(runId, arg, options);
  }
}
export const getAddItemsMutationKey = (runId: string,) => [`/api/v1/runs/${runId}/items`] as const;

export type AddItemsMutationResult = NonNullable<Awaited<ReturnType<typeof addItems>>>
export type AddItemsMutationError = AxiosError<unknown>

export const useAddItems = <TError = AxiosError<unknown>>(
  runId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof addItems>>, TError, Key, AddItemsRequest, Awaited<ReturnType<typeof addItems>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAddItemsMutationKey(runId);
  const swrFn = getAddItemsMutationFetcher(runId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const getRunDetails = (
    runId: string,
    params: GetRunDetailsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RunDetails>> => {
    return axios.default.get(
      `/api/v1/runs/${runId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getGetRunDetailsKey = (runId: string,
    params: GetRunDetailsParams,) => [`/api/v1/runs/${runId}`, ...(params ? [params]: [])] as const;

export type GetRunDetailsQueryResult = NonNullable<Awaited<ReturnType<typeof getRunDetails>>>
export type GetRunDetailsQueryError = AxiosError<unknown>

export const useGetRunDetails = <TError = AxiosError<unknown>>(
  runId: string,
    params: GetRunDetailsParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getRunDetails>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(runId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetRunDetailsKey(runId,params) : null);
  const swrFn = () => getRunDetails(runId,params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const updateRun = (
    runId: string,
    updateRunRequest: UpdateRunRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UpdateRun200>> => {
    return axios.default.patch(
      `/api/v1/runs/${runId}`,
      updateRunRequest,options
    );
  }



export const getUpdateRunMutationFetcher = (runId: string, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: UpdateRunRequest }) => {
    return updateRun(runId, arg, options);
  }
}
export const getUpdateRunMutationKey = (runId: string,) => [`/api/v1/runs/${runId}`] as const;

export type UpdateRunMutationResult = NonNullable<Awaited<ReturnType<typeof updateRun>>>
export type UpdateRunMutationError = AxiosError<unknown>

export const useUpdateRun = <TError = AxiosError<unknown>>(
  runId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateRun>>, TError, Key, UpdateRunRequest, Awaited<ReturnType<typeof updateRun>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateRunMutationKey(runId);
  const swrFn = getUpdateRunMutationFetcher(runId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
