/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  AnnotationRequest,
  AnnotationView
} from '../generated.schemas';



  
  
  
export const get = (
    runId: string,
    itemResultId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AnnotationView>> => {
    return axios.default.get(
      `/api/v1/runs/${runId}/items/${itemResultId}/annotation`,options
    );
  }



export const getGetKey = (runId: string,
    itemResultId: string,) => [`/api/v1/runs/${runId}/items/${itemResultId}/annotation`] as const;

export type GetQueryResult = NonNullable<Awaited<ReturnType<typeof get>>>

export const useGet = <TError = AxiosError<unknown>>(
  runId: string,
    itemResultId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof get>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(runId && itemResultId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetKey(runId,itemResultId) : null);
  const swrFn = () => get(runId,itemResultId, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const upsert = (
    runId: string,
    itemResultId: string,
    annotationRequest: AnnotationRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AnnotationView>> => {
    return axios.default.put(
      `/api/v1/runs/${runId}/items/${itemResultId}/annotation`,
      annotationRequest,options
    );
  }



export const getUpsertMutationFetcher = (runId: string,
    itemResultId: string, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: AnnotationRequest }) => {
    return upsert(runId, itemResultId, arg, options);
  }
}
export const getUpsertMutationKey = (runId: string,
    itemResultId: string,) => [`/api/v1/runs/${runId}/items/${itemResultId}/annotation`] as const;

export type UpsertMutationResult = NonNullable<Awaited<ReturnType<typeof upsert>>>

export const useUpsert = <TError = AxiosError<unknown>>(
  runId: string,
    itemResultId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof upsert>>, TError, Key, AnnotationRequest, Awaited<ReturnType<typeof upsert>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpsertMutationKey(runId,itemResultId);
  const swrFn = getUpsertMutationFetcher(runId,itemResultId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const _delete = (
    runId: string,
    itemResultId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.default.delete(
      `/api/v1/runs/${runId}/items/${itemResultId}/annotation`,options
    );
  }



export const getDeleteMutationFetcher = (runId: string,
    itemResultId: string, options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return _delete(runId, itemResultId, options);
  }
}
export const getDeleteMutationKey = (runId: string,
    itemResultId: string,) => [`/api/v1/runs/${runId}/items/${itemResultId}/annotation`] as const;

export type _DeleteMutationResult = NonNullable<Awaited<ReturnType<typeof _delete>>>

export const useDelete = <TError = AxiosError<unknown>>(
  runId: string,
    itemResultId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof _delete>>, TError, Key, Arguments, Awaited<ReturnType<typeof _delete>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteMutationKey(runId,itemResultId);
  const swrFn = getDeleteMutationFetcher(runId,itemResultId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
