/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ListTracesParams,
  OtlpExportTraceServiceRequest,
  PageResponseTraceSummary,
  TraceDetail,
  TraceIngestResponse
} from '../generated.schemas';



  
  
  
export const listTraces = (
    params?: ListTracesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PageResponseTraceSummary>> => {
    return axios.default.get(
      `/api/v1/traces`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getListTracesKey = (params?: ListTracesParams,) => [`/api/v1/traces`, ...(params ? [params]: [])] as const;

export type ListTracesQueryResult = NonNullable<Awaited<ReturnType<typeof listTraces>>>

export const useListTraces = <TError = AxiosError<unknown>>(
  params?: ListTracesParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listTraces>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListTracesKey(params) : null);
  const swrFn = () => listTraces(params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const ingestTraces = (
    otlpExportTraceServiceRequest: OtlpExportTraceServiceRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TraceIngestResponse>> => {
    return axios.default.post(
      `/api/v1/traces`,
      otlpExportTraceServiceRequest,options
    );
  }



export const getIngestTracesMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: OtlpExportTraceServiceRequest }) => {
    return ingestTraces(arg, options);
  }
}
export const getIngestTracesMutationKey = () => [`/api/v1/traces`] as const;

export type IngestTracesMutationResult = NonNullable<Awaited<ReturnType<typeof ingestTraces>>>

export const useIngestTraces = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof ingestTraces>>, TError, Key, OtlpExportTraceServiceRequest, Awaited<ReturnType<typeof ingestTraces>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getIngestTracesMutationKey();
  const swrFn = getIngestTracesMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const getTrace = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TraceDetail>> => {
    return axios.default.get(
      `/api/v1/traces/${id}`,options
    );
  }



export const getGetTraceKey = (id: string,) => [`/api/v1/traces/${id}`] as const;

export type GetTraceQueryResult = NonNullable<Awaited<ReturnType<typeof getTrace>>>

export const useGetTrace = <TError = AxiosError<unknown>>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTrace>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTraceKey(id) : null);
  const swrFn = () => getTrace(id, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
