/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  ApiKeyView,
  CreateApiKeyRequest,
  CreatedApiKeyView
} from '../generated.schemas';



  
  
  
export const listApiKeys = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiKeyView[]>> => {
    return axios.default.get(
      `/api/v1/api-keys`,options
    );
  }



export const getListApiKeysKey = () => [`/api/v1/api-keys`] as const;

export type ListApiKeysQueryResult = NonNullable<Awaited<ReturnType<typeof listApiKeys>>>

export const useListApiKeys = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listApiKeys>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListApiKeysKey() : null);
  const swrFn = () => listApiKeys(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const createApiKey = (
    createApiKeyRequest: CreateApiKeyRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreatedApiKeyView>> => {
    return axios.default.post(
      `/api/v1/api-keys`,
      createApiKeyRequest,options
    );
  }



export const getCreateApiKeyMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: CreateApiKeyRequest }) => {
    return createApiKey(arg, options);
  }
}
export const getCreateApiKeyMutationKey = () => [`/api/v1/api-keys`] as const;

export type CreateApiKeyMutationResult = NonNullable<Awaited<ReturnType<typeof createApiKey>>>

export const useCreateApiKey = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createApiKey>>, TError, Key, CreateApiKeyRequest, Awaited<ReturnType<typeof createApiKey>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateApiKeyMutationKey();
  const swrFn = getCreateApiKeyMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const disableApiKey = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiKeyView>> => {
    return axios.default.post(
      `/api/v1/api-keys/${id}/disable`,undefined,options
    );
  }



export const getDisableApiKeyMutationFetcher = (id: string, options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return disableApiKey(id, options);
  }
}
export const getDisableApiKeyMutationKey = (id: string,) => [`/api/v1/api-keys/${id}/disable`] as const;

export type DisableApiKeyMutationResult = NonNullable<Awaited<ReturnType<typeof disableApiKey>>>

export const useDisableApiKey = <TError = AxiosError<unknown>>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof disableApiKey>>, TError, Key, Arguments, Awaited<ReturnType<typeof disableApiKey>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDisableApiKeyMutationKey(id);
  const swrFn = getDisableApiKeyMutationFetcher(id, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const deleteApiKey = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.default.delete(
      `/api/v1/api-keys/${id}`,options
    );
  }



export const getDeleteApiKeyMutationFetcher = (id: string, options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteApiKey(id, options);
  }
}
export const getDeleteApiKeyMutationKey = (id: string,) => [`/api/v1/api-keys/${id}`] as const;

export type DeleteApiKeyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiKey>>>

export const useDeleteApiKey = <TError = AxiosError<unknown>>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteApiKey>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteApiKey>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteApiKeyMutationKey(id);
  const swrFn = getDeleteApiKeyMutationFetcher(id, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
