/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface AddItemsRequest {
  /** @minItems 1 */
  items?: ItemData[];
}

export type EvalDataMetadata = {[key: string]: { [key: string]: unknown }};

export interface EvalData {
  name?: string;
  score?: number;
  threshold?: number;
  success?: boolean;
  reason?: string;
  metadata?: EvalDataMetadata;
}

export type ItemDataInputs = {[key: string]: { [key: string]: unknown }};

export type ItemDataExpectedOutputs = {[key: string]: { [key: string]: unknown }};

export type ItemDataActualOutputs = {[key: string]: { [key: string]: unknown }};

export interface ItemData {
  inputs?: ItemDataInputs;
  expectedOutputs?: ItemDataExpectedOutputs;
  actualOutputs?: ItemDataActualOutputs;
  evalResults?: EvalData[];
  success?: boolean;
}

export type CreateRunRequestMetadata = {[key: string]: { [key: string]: unknown }};

export interface CreateRunRequest {
  /** @minLength 1 */
  experimentName: string;
  metadata?: CreateRunRequestMetadata;
}

export interface CreateRunResponse {
  runId?: string;
}

export type UpdateRunRequestStatus = typeof UpdateRunRequestStatus[keyof typeof UpdateRunRequestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateRunRequestStatus = {
  RUNNING: 'RUNNING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export interface UpdateRunRequest {
  status: UpdateRunRequestStatus;
}

export interface Pageable {
  /** @minimum 0 */
  page?: number;
  /** @minimum 1 */
  size?: number;
  sort?: string[];
}

export interface EvalSummary {
  id?: string;
  evaluatorName?: string;
  score?: number;
  threshold?: number;
  success?: boolean;
  reason?: string;
}

export type ItemSummaryMetadata = {[key: string]: { [key: string]: unknown }};

export interface ItemSummary {
  id?: string;
  input?: string;
  expectedOutput?: string;
  actualOutput?: string;
  metadata?: ItemSummaryMetadata;
  evalResults?: EvalSummary[];
  createdAt?: string;
}

export interface PageItemSummary {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: ItemSummary[];
  number?: number;
  sort?: SortObject;
  first?: boolean;
  pageable?: PageableObject;
  last?: boolean;
  numberOfElements?: number;
  empty?: boolean;
}

export interface PageableObject {
  offset?: number;
  sort?: SortObject;
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  unpaged?: boolean;
}

export type RunDetailsStatus = typeof RunDetailsStatus[keyof typeof RunDetailsStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunDetailsStatus = {
  RUNNING: 'RUNNING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export type RunDetailsConfig = {[key: string]: { [key: string]: unknown }};

export interface RunDetails {
  id?: string;
  experimentId?: string;
  experimentName?: string;
  projectName?: string;
  status?: RunDetailsStatus;
  config?: RunDetailsConfig;
  totalItems?: number;
  passedItems?: number;
  passRate?: number;
  startedAt?: string;
  completedAt?: string;
  items?: PageItemSummary;
}

export interface SortObject {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}

export interface ProjectSummary {
  id?: string;
  name?: string;
  experimentCount?: number;
  createdAt?: string;
}

export interface ExperimentSummary {
  id?: string;
  name?: string;
  createdAt?: string;
  latestRun?: LatestRunInfo;
}

export type LatestRunInfoStatus = typeof LatestRunInfoStatus[keyof typeof LatestRunInfoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LatestRunInfoStatus = {
  RUNNING: 'RUNNING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export interface LatestRunInfo {
  runId?: string;
  status?: LatestRunInfoStatus;
  passRate?: number;
  startedAt?: string;
}

export interface RunPoint {
  runId?: string;
  startedAt?: string;
  passRate?: number;
  totalItems?: number;
  passedItems?: number;
}

export interface TrendData {
  experimentName?: string;
  projectName?: string;
  runs?: RunPoint[];
}

export type RunSummaryStatus = typeof RunSummaryStatus[keyof typeof RunSummaryStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunSummaryStatus = {
  RUNNING: 'RUNNING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export type RunSummaryConfig = {[key: string]: { [key: string]: unknown }};

export interface RunSummary {
  id?: string;
  status?: RunSummaryStatus;
  config?: RunSummaryConfig;
  itemCount?: number;
  passedCount?: number;
  passRate?: number;
  startedAt?: string;
  completedAt?: string;
}

export type AddItems201 = {[key: string]: string};

export type GetRunDetailsParams = {
pageable: Pageable;
};

export type UpdateRun200 = {[key: string]: string};

export type GetTrendsParams = {
limit?: number;
};

