/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export type AnnotationRequestVerdict = typeof AnnotationRequestVerdict[keyof typeof AnnotationRequestVerdict];


export const AnnotationRequestVerdict = {
  CORRECT: 'CORRECT',
  INCORRECT: 'INCORRECT',
  UNSURE: 'UNSURE',
} as const;

export type AnnotationRequestOverriddenExpectedOutput = {[key: string]: { [key: string]: unknown }};

export interface AnnotationRequest {
  verdict: AnnotationRequestVerdict;
  overriddenExpectedOutput?: AnnotationRequestOverriddenExpectedOutput;
  /**
   * @minLength 0
   * @maxLength 10000
   */
  note?: string;
}

export type AnnotationViewVerdict = typeof AnnotationViewVerdict[keyof typeof AnnotationViewVerdict];


export const AnnotationViewVerdict = {
  CORRECT: 'CORRECT',
  INCORRECT: 'INCORRECT',
  UNSURE: 'UNSURE',
} as const;

export type AnnotationViewOverriddenExpectedOutput = {[key: string]: { [key: string]: unknown }};

export interface AnnotationView {
  id?: string;
  verdict?: AnnotationViewVerdict;
  overriddenExpectedOutput?: AnnotationViewOverriddenExpectedOutput;
  note?: string;
  createdBy?: string;
  createdAt?: string;
  updatedAt?: string;
}

export type CreateTraceEvalRuleRequestMatchType = typeof CreateTraceEvalRuleRequestMatchType[keyof typeof CreateTraceEvalRuleRequestMatchType];


export const CreateTraceEvalRuleRequestMatchType = {
  SPAN_NAME: 'SPAN_NAME',
  ATTRIBUTE: 'ATTRIBUTE',
} as const;

export interface CreateTraceEvalRuleRequest {
  /** @minLength 1 */
  name?: string;
  enabled?: boolean;
  matchType: CreateTraceEvalRuleRequestMatchType;
  matchKey?: string;
  /** @minLength 1 */
  matchValue?: string;
  connectionId: string;
  /** @minLength 1 */
  evaluatorName?: string;
  /** @minLength 1 */
  criteria?: string;
  minScore?: number;
  maxScore?: number;
  threshold?: number;
}

export type TraceEvalRuleViewMatchType = typeof TraceEvalRuleViewMatchType[keyof typeof TraceEvalRuleViewMatchType];


export const TraceEvalRuleViewMatchType = {
  SPAN_NAME: 'SPAN_NAME',
  ATTRIBUTE: 'ATTRIBUTE',
} as const;

export interface TraceEvalRuleView {
  id?: string;
  projectId?: string;
  name?: string;
  enabled?: boolean;
  matchType?: TraceEvalRuleViewMatchType;
  matchKey?: string;
  matchValue?: string;
  connectionId?: string;
  evaluatorName?: string;
  criteria?: string;
  minScore?: number;
  maxScore?: number;
  threshold?: number;
  createdAt?: string;
  updatedAt?: string;
}

export type UpdateLlmConnectionRequestProtocol = typeof UpdateLlmConnectionRequestProtocol[keyof typeof UpdateLlmConnectionRequestProtocol];


export const UpdateLlmConnectionRequestProtocol = {
  RESPONSES: 'RESPONSES',
  CHAT_COMPLETIONS: 'CHAT_COMPLETIONS',
} as const;

export interface UpdateLlmConnectionRequest {
  /** @minLength 1 */
  name?: string;
  /** @minLength 1 */
  baseUrl?: string;
  /** @minLength 1 */
  model?: string;
  protocol?: UpdateLlmConnectionRequestProtocol;
  apiKey?: string;
  credentialRef?: string;
}

export type LlmConnectionViewProtocol = typeof LlmConnectionViewProtocol[keyof typeof LlmConnectionViewProtocol];


export const LlmConnectionViewProtocol = {
  RESPONSES: 'RESPONSES',
  CHAT_COMPLETIONS: 'CHAT_COMPLETIONS',
} as const;

export interface LlmConnectionView {
  id?: string;
  name?: string;
  baseUrl?: string;
  model?: string;
  protocol?: LlmConnectionViewProtocol;
  credentialRef?: string;
  hasInlineKey?: boolean;
  createdAt?: string;
}

export interface OtlpAnyValue {
  stringValue?: string;
  boolValue?: boolean;
  intValue?: string;
  doubleValue?: number;
}

export interface OtlpKeyValue {
  key?: string;
  value?: OtlpAnyValue;
}

export interface OtlpResource {
  attributes?: OtlpKeyValue[];
}

export interface OtlpStatus {
  code?: string;
  message?: string;
}

export interface OtlpSpan {
  traceId?: string;
  spanId?: string;
  parentSpanId?: string;
  name?: string;
  kind?: string;
  startTimeUnixNano?: string;
  endTimeUnixNano?: string;
  status?: OtlpStatus;
  attributes?: OtlpKeyValue[];
}

export interface OtlpScopeSpans {
  spans?: OtlpSpan[];
}

export interface OtlpResourceSpans {
  resource?: OtlpResource;
  scopeSpans?: OtlpScopeSpans[];
}

export interface OtlpExportTraceServiceRequest {
  resourceSpans?: OtlpResourceSpans[];
}

export interface TraceIngestResponse {
  acceptedSpans?: number;
  rejectedSpans?: number;
  traces?: number;
}

export interface EnqueueJudgeRequest {
  connectionId: string;
  /** @minLength 1 */
  evaluatorName?: string;
  /** @minLength 1 */
  criteria?: string;
  evaluationParams?: string[];
  minScore?: number;
  maxScore?: number;
  threshold?: number;
}

export type EvalJobViewStatus = typeof EvalJobViewStatus[keyof typeof EvalJobViewStatus];


export const EvalJobViewStatus = {
  PENDING: 'PENDING',
  CLAIMED: 'CLAIMED',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
} as const;

export interface EvalJobView {
  id?: string;
  runId?: string;
  connectionId?: string;
  evaluatorName?: string;
  status?: EvalJobViewStatus;
  attemptCount?: number;
  lastError?: string;
  createdAt?: string;
  claimedAt?: string;
  completedAt?: string;
}

export type EvalDataMetadata = {[key: string]: { [key: string]: unknown }};

export interface EvalData {
  name?: string;
  score?: number;
  threshold?: number;
  success?: boolean;
  reason?: string;
  metadata?: EvalDataMetadata;
}

export type ItemDataInputs = {[key: string]: { [key: string]: unknown }};

export type ItemDataExpectedOutputs = {[key: string]: { [key: string]: unknown }};

export type ItemDataActualOutputs = {[key: string]: { [key: string]: unknown }};

export type ItemDataMetadata = {[key: string]: { [key: string]: unknown }};

export interface ItemData {
  inputs?: ItemDataInputs;
  expectedOutputs?: ItemDataExpectedOutputs;
  actualOutputs?: ItemDataActualOutputs;
  metadata?: ItemDataMetadata;
  evalResults?: EvalData[];
  success?: boolean;
  datasetItemId?: string;
  tokensIn?: number;
  tokensOut?: number;
  costUsd?: number;
  latencyMs?: number;
}

export interface AddItemsRequest {
  /** @minItems 1 */
  items?: ItemData[];
}

export type CreateRunRequestMetadata = {[key: string]: { [key: string]: unknown }};

export interface CreateRunRequest {
  /** @minLength 1 */
  experimentName: string;
  metadata?: CreateRunRequestMetadata;
  name?: string;
  gitSha?: string;
  gitBranch?: string;
  triggeredBy?: string;
  datasetName?: string;
  /** @minimum 1 */
  datasetVersion?: number;
}

export interface CreateRunResponse {
  runId?: string;
}

export type CreateLlmConnectionRequestProtocol = typeof CreateLlmConnectionRequestProtocol[keyof typeof CreateLlmConnectionRequestProtocol];


export const CreateLlmConnectionRequestProtocol = {
  RESPONSES: 'RESPONSES',
  CHAT_COMPLETIONS: 'CHAT_COMPLETIONS',
} as const;

export interface CreateLlmConnectionRequest {
  /** @minLength 1 */
  name?: string;
  /** @minLength 1 */
  baseUrl?: string;
  /** @minLength 1 */
  model?: string;
  protocol?: CreateLlmConnectionRequestProtocol;
  apiKey?: string;
  credentialRef?: string;
}

export interface GateRequest {
  candidateRunId: string;
  baselineRunId?: string;
  baselineBranch?: string;
}

export interface EvaluatorDrop {
  evaluator?: string;
  baselineMean?: number;
  candidateMean?: number;
  delta?: number;
}

export interface RegressedEvaluator {
  evaluator?: string;
  baselineMean?: number;
  candidateMean?: number;
  delta?: number;
  pValue?: number;
}

export interface RegressedCase {
  datasetItemId?: string;
  index?: string;
  evaluatorDrops?: EvaluatorDrop[];
}

export interface GateResult {
  status?: string;
  passed?: boolean;
  candidateRunId?: string;
  baselineRunId?: string;
  pairing?: string;
  baselinePassRate?: number;
  candidatePassRate?: number;
  passRateDelta?: number;
  significant?: boolean;
  improvedCount?: number;
  regressedCount?: number;
  unchangedCount?: number;
  addedCount?: number;
  removedCount?: number;
  regressedEvaluators?: RegressedEvaluator[];
  cases?: RegressedCase[];
  casesTruncated?: boolean;
}

export interface CreateDatasetRequest {
  /** @minLength 1 */
  name?: string;
  description?: string;
}

export interface DatasetSummary {
  id?: string;
  name?: string;
  description?: string;
  latestVersion?: number;
  latestItemCount?: number;
  createdAt?: string;
  updatedAt?: string;
}

export type ItemPayloadInputs = {[key: string]: { [key: string]: unknown }};

export type ItemPayloadExpectedOutputs = {[key: string]: { [key: string]: unknown }};

export type ItemPayloadMetadata = {[key: string]: { [key: string]: unknown }};

export interface ItemPayload {
  inputs: ItemPayloadInputs;
  expectedOutputs?: ItemPayloadExpectedOutputs;
  metadata?: ItemPayloadMetadata;
}

export interface CreateVersionRequest {
  description?: string;
  /** @minItems 1 */
  items?: ItemPayload[];
}

export interface DatasetVersionDetails {
  id?: string;
  datasetName?: string;
  version?: number;
  description?: string;
  itemCount?: number;
  createdAt?: string;
  createdBy?: string;
}

export type PromoteItemOverriddenExpectedOutput = {[key: string]: { [key: string]: unknown }};

export interface PromoteItem {
  itemResultId: string;
  overriddenExpectedOutput?: PromoteItemOverriddenExpectedOutput;
}

export interface PromoteRequest {
  /** @minLength 1 */
  datasetName?: string;
  /**
   * @minLength 0
   * @maxLength 2000
   */
  description?: string;
  /** @minItems 1 */
  items?: PromoteItem[];
}

export type UpdateRunRequestStatus = typeof UpdateRunRequestStatus[keyof typeof UpdateRunRequestStatus];


export const UpdateRunRequestStatus = {
  RUNNING: 'RUNNING',
  EVALUATING: 'EVALUATING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export interface UpdateRunRequest {
  status: UpdateRunRequestStatus;
}

export interface TraceSummary {
  id?: string;
  traceId?: string;
  projectId?: string;
  rootSpanName?: string;
  spanCount?: number;
  createdAt?: string;
  expiresAt?: string;
}

export interface PageSort {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}

export interface PageablePage {
  offset?: number;
  sort?: PageSort;
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  unpaged?: boolean;
}

export interface PageResponseTraceSummary {
  content?: TraceSummary[];
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  empty?: boolean;
  sort?: PageSort;
  pageable?: PageablePage;
}

export type SpanViewAttributes = {[key: string]: { [key: string]: unknown }};

export interface SpanView {
  id?: string;
  spanId?: string;
  parentSpanId?: string;
  name?: string;
  kind?: string;
  statusCode?: string;
  startTimeUnixNano?: number;
  endTimeUnixNano?: number;
  inputText?: string;
  outputText?: string;
  attributes?: SpanViewAttributes;
}

export type TraceEvalJobViewStatus = typeof TraceEvalJobViewStatus[keyof typeof TraceEvalJobViewStatus];


export const TraceEvalJobViewStatus = {
  PENDING: 'PENDING',
  CLAIMED: 'CLAIMED',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
} as const;

export interface TraceEvalJobView {
  id?: string;
  spanId?: string;
  ruleId?: string;
  evaluatorName?: string;
  status?: TraceEvalJobViewStatus;
  score?: number;
  success?: boolean;
  reason?: string;
  attemptCount?: number;
  lastError?: string;
  createdAt?: string;
  completedAt?: string;
}

export interface TraceDetail {
  id?: string;
  traceId?: string;
  projectId?: string;
  tenantId?: string;
  rootSpanName?: string;
  spanCount?: number;
  startTimeUnixNano?: number;
  endTimeUnixNano?: number;
  createdAt?: string;
  expiresAt?: string;
  spans?: SpanView[];
  evalJobs?: TraceEvalJobView[];
}

export interface Pageable {
  /** @minimum 0 */
  page?: number;
  /** @minimum 1 */
  size?: number;
  sort?: string[];
}

export interface EvalSummary {
  id?: string;
  evaluatorName?: string;
  score?: number;
  threshold?: number;
  success?: boolean;
  reason?: string;
}

export type ItemSummaryInput = {[key: string]: { [key: string]: unknown }};

export type ItemSummaryExpectedOutput = {[key: string]: { [key: string]: unknown }};

export type ItemSummaryActualOutput = {[key: string]: { [key: string]: unknown }};

export type ItemSummaryMetadata = {[key: string]: { [key: string]: unknown }};

export interface ItemSummary {
  id?: string;
  input?: ItemSummaryInput;
  expectedOutput?: ItemSummaryExpectedOutput;
  actualOutput?: ItemSummaryActualOutput;
  metadata?: ItemSummaryMetadata;
  evalResults?: EvalSummary[];
  createdAt?: string;
  datasetItemId?: string;
  annotation?: AnnotationView;
  tokensIn?: number;
  tokensOut?: number;
  costUsd?: number;
  latencyMs?: number;
}

export interface SortObject {
  empty?: boolean;
  unsorted?: boolean;
  sorted?: boolean;
}

export interface PageableObject {
  offset?: number;
  sort?: SortObject;
  unpaged?: boolean;
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
}

export interface PageItemSummary {
  totalPages?: number;
  totalElements?: number;
  first?: boolean;
  last?: boolean;
  size?: number;
  content?: ItemSummary[];
  number?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  numberOfElements?: number;
  empty?: boolean;
}

export type RunDetailsStatus = typeof RunDetailsStatus[keyof typeof RunDetailsStatus];


export const RunDetailsStatus = {
  RUNNING: 'RUNNING',
  EVALUATING: 'EVALUATING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export type RunDetailsConfig = {[key: string]: { [key: string]: unknown }};

export interface RunDetails {
  id?: string;
  experimentId?: string;
  experimentName?: string;
  projectName?: string;
  status?: RunDetailsStatus;
  config?: RunDetailsConfig;
  totalItems?: number;
  passedItems?: number;
  passRate?: number;
  startedAt?: string;
  completedAt?: string;
  datasetVersionId?: string;
  datasetVersion?: number;
  totalTokensIn?: number;
  totalTokensOut?: number;
  totalCostUsd?: number;
  avgLatencyMs?: number;
  items?: PageItemSummary;
}

export interface EvaluatorAlignment {
  evaluatorName?: string;
  comparableCount?: number;
  agreedCount?: number;
  excludedUnsure?: number;
  alignmentRate?: number;
}

export interface AlignmentView {
  annotatedItems?: number;
  evaluators?: EvaluatorAlignment[];
}

export type ReviewQueueItemCurrentVerdict = typeof ReviewQueueItemCurrentVerdict[keyof typeof ReviewQueueItemCurrentVerdict];


export const ReviewQueueItemCurrentVerdict = {
  CORRECT: 'CORRECT',
  INCORRECT: 'INCORRECT',
  UNSURE: 'UNSURE',
} as const;

export type ReviewQueueItemInput = {[key: string]: { [key: string]: unknown }};

export type ReviewQueueItemExpectedOutput = {[key: string]: { [key: string]: unknown }};

export type ReviewQueueItemActualOutput = {[key: string]: { [key: string]: unknown }};

export interface ReviewQueueItem {
  itemId?: string;
  runId?: string;
  experimentId?: string;
  experimentName?: string;
  projectName?: string;
  input?: ReviewQueueItemInput;
  expectedOutput?: ReviewQueueItemExpectedOutput;
  actualOutput?: ReviewQueueItemActualOutput;
  evalResults?: EvalSummary[];
  currentVerdict?: ReviewQueueItemCurrentVerdict;
  createdAt?: string;
}

export interface PageReviewQueueItem {
  totalPages?: number;
  totalElements?: number;
  first?: boolean;
  last?: boolean;
  size?: number;
  content?: ReviewQueueItem[];
  number?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  numberOfElements?: number;
  empty?: boolean;
}

export interface ProjectSummary {
  id?: string;
  name?: string;
  experimentCount?: number;
  createdAt?: string;
}

export type LatestRunInfoStatus = typeof LatestRunInfoStatus[keyof typeof LatestRunInfoStatus];


export const LatestRunInfoStatus = {
  RUNNING: 'RUNNING',
  EVALUATING: 'EVALUATING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export interface LatestRunInfo {
  runId?: string;
  status?: LatestRunInfoStatus;
  passRate?: number;
  startedAt?: string;
}

export interface ExperimentSummary {
  id?: string;
  name?: string;
  createdAt?: string;
  latestRun?: LatestRunInfo;
}

export interface RunPoint {
  runId?: string;
  startedAt?: string;
  passRate?: number;
  totalItems?: number;
  passedItems?: number;
}

export interface TrendData {
  experimentName?: string;
  projectName?: string;
  runs?: RunPoint[];
}

export type RunSummaryStatus = typeof RunSummaryStatus[keyof typeof RunSummaryStatus];


export const RunSummaryStatus = {
  RUNNING: 'RUNNING',
  EVALUATING: 'EVALUATING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export type RunSummaryConfig = {[key: string]: { [key: string]: unknown }};

export interface RunSummary {
  id?: string;
  status?: RunSummaryStatus;
  config?: RunSummaryConfig;
  itemCount?: number;
  passedCount?: number;
  passRate?: number;
  startedAt?: string;
  completedAt?: string;
  datasetVersionId?: string;
  datasetVersion?: number;
  totalTokensIn?: number;
  totalTokensOut?: number;
  totalCostUsd?: number;
  avgLatencyMs?: number;
}

export interface EvaluatorDiff {
  name?: string;
  baselineMean?: number;
  candidateMean?: number;
  delta?: number;
  status?: string;
  significant?: boolean;
}

export interface DiffCase {
  datasetItemId?: string;
  index?: string;
  status?: string;
  passFlip?: boolean;
  input?: string;
  evaluators?: EvaluatorDiff[];
}

export interface DiffSummary {
  pairing?: string;
  baselineRunId?: string;
  candidateRunId?: string;
  baselinePassRate?: number;
  candidatePassRate?: number;
  passRateDelta?: number;
  significant?: boolean;
  improvedCount?: number;
  regressedCount?: number;
  unchangedCount?: number;
  addedCount?: number;
  removedCount?: number;
}

export interface PageResponseDiffCase {
  content?: DiffCase[];
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  empty?: boolean;
  sort?: PageSort;
  pageable?: PageablePage;
}

export interface DiffView {
  summary?: DiffSummary;
  cases?: PageResponseDiffCase;
}

export interface VersionSummary {
  id?: string;
  version?: number;
  description?: string;
  itemCount?: number;
  createdAt?: string;
  createdBy?: string;
}

export interface DatasetDetails {
  id?: string;
  name?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  versions?: VersionSummary[];
}

export type DatasetItemViewInputs = {[key: string]: { [key: string]: unknown }};

export type DatasetItemViewExpectedOutputs = {[key: string]: { [key: string]: unknown }};

export type DatasetItemViewMetadata = {[key: string]: { [key: string]: unknown }};

export interface DatasetItemView {
  id?: string;
  ordinal?: number;
  inputs?: DatasetItemViewInputs;
  expectedOutputs?: DatasetItemViewExpectedOutputs;
  metadata?: DatasetItemViewMetadata;
}

export interface PageResponseDatasetItemView {
  content?: DatasetItemView[];
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  empty?: boolean;
  sort?: PageSort;
  pageable?: PageablePage;
}

export type ListTracesParams = {
projectId?: string;
page?: number;
size?: number;
};

export type AddItems201 = {[key: string]: string};

export type GetRunDetailsParams = {
pageable: Pageable;
};

export type UpdateRun200 = {[key: string]: string};

export type List2Params = {
projectName?: string;
experimentId?: string;
runId?: string;
pageable: Pageable;
};

export type GetTrendsParams = {
limit?: number;
};

export type DiffParams = {
baselineRunId: string;
status?: string;
pageable: Pageable;
};

export type ListItemsParams = {
pageable: Pageable;
};

