/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export type AnnotationRequestVerdict = typeof AnnotationRequestVerdict[keyof typeof AnnotationRequestVerdict];


export const AnnotationRequestVerdict = {
  CORRECT: 'CORRECT',
  INCORRECT: 'INCORRECT',
  UNSURE: 'UNSURE',
} as const;

export type AnnotationRequestOverriddenExpectedOutput = {[key: string]: { [key: string]: unknown }};

export interface AnnotationRequest {
  verdict: AnnotationRequestVerdict;
  overriddenExpectedOutput?: AnnotationRequestOverriddenExpectedOutput;
  note?: string;
}

export type AnnotationViewVerdict = typeof AnnotationViewVerdict[keyof typeof AnnotationViewVerdict];


export const AnnotationViewVerdict = {
  CORRECT: 'CORRECT',
  INCORRECT: 'INCORRECT',
  UNSURE: 'UNSURE',
} as const;

export type AnnotationViewOverriddenExpectedOutput = {[key: string]: { [key: string]: unknown }};

export interface AnnotationView {
  id?: string;
  verdict?: AnnotationViewVerdict;
  overriddenExpectedOutput?: AnnotationViewOverriddenExpectedOutput;
  note?: string;
  createdBy?: string;
  createdAt?: string;
  updatedAt?: string;
}

export type EvalDataMetadata = {[key: string]: { [key: string]: unknown }};

export interface EvalData {
  name?: string;
  score?: number;
  threshold?: number;
  success?: boolean;
  reason?: string;
  metadata?: EvalDataMetadata;
}

export type ItemDataInputs = {[key: string]: { [key: string]: unknown }};

export type ItemDataExpectedOutputs = {[key: string]: { [key: string]: unknown }};

export type ItemDataActualOutputs = {[key: string]: { [key: string]: unknown }};

export type ItemDataMetadata = {[key: string]: { [key: string]: unknown }};

export interface ItemData {
  inputs?: ItemDataInputs;
  expectedOutputs?: ItemDataExpectedOutputs;
  actualOutputs?: ItemDataActualOutputs;
  metadata?: ItemDataMetadata;
  evalResults?: EvalData[];
  success?: boolean;
  datasetItemId?: string;
}

export interface AddItemsRequest {
  /** @minItems 1 */
  items?: ItemData[];
}

export type CreateRunRequestMetadata = {[key: string]: { [key: string]: unknown }};

export interface CreateRunRequest {
  /** @minLength 1 */
  experimentName: string;
  metadata?: CreateRunRequestMetadata;
  name?: string;
  gitSha?: string;
  gitBranch?: string;
  triggeredBy?: string;
  datasetName?: string;
  /** @minimum 1 */
  datasetVersion?: number;
}

export interface CreateRunResponse {
  runId?: string;
}

export interface GateRequest {
  candidateRunId: string;
  baselineRunId?: string;
  baselineBranch?: string;
}

export interface EvaluatorDrop {
  evaluator?: string;
  baselineMean?: number;
  candidateMean?: number;
  delta?: number;
}

export interface RegressedEvaluator {
  evaluator?: string;
  baselineMean?: number;
  candidateMean?: number;
  delta?: number;
  pValue?: number;
}

export interface RegressedCase {
  datasetItemId?: string;
  index?: string;
  evaluatorDrops?: EvaluatorDrop[];
}

export interface GateResult {
  status?: string;
  passed?: boolean;
  candidateRunId?: string;
  baselineRunId?: string;
  pairing?: string;
  baselinePassRate?: number;
  candidatePassRate?: number;
  passRateDelta?: number;
  significant?: boolean;
  improvedCount?: number;
  regressedCount?: number;
  unchangedCount?: number;
  addedCount?: number;
  removedCount?: number;
  regressedEvaluators?: RegressedEvaluator[];
  cases?: RegressedCase[];
  casesTruncated?: boolean;
}

export interface CreateDatasetRequest {
  /** @minLength 1 */
  name?: string;
  description?: string;
}

export interface DatasetSummary {
  id?: string;
  name?: string;
  description?: string;
  latestVersion?: number;
  latestItemCount?: number;
  createdAt?: string;
  updatedAt?: string;
}

export type ItemPayloadInputs = {[key: string]: { [key: string]: unknown }};

export type ItemPayloadExpectedOutputs = {[key: string]: { [key: string]: unknown }};

export type ItemPayloadMetadata = {[key: string]: { [key: string]: unknown }};

export interface ItemPayload {
  inputs: ItemPayloadInputs;
  expectedOutputs?: ItemPayloadExpectedOutputs;
  metadata?: ItemPayloadMetadata;
}

export interface CreateVersionRequest {
  description?: string;
  /** @minItems 1 */
  items?: ItemPayload[];
}

export interface DatasetVersionDetails {
  id?: string;
  datasetName?: string;
  version?: number;
  description?: string;
  itemCount?: number;
  createdAt?: string;
  createdBy?: string;
}

export type PromoteItemOverriddenExpectedOutput = {[key: string]: { [key: string]: unknown }};

export interface PromoteItem {
  itemResultId: string;
  overriddenExpectedOutput?: PromoteItemOverriddenExpectedOutput;
}

export interface PromoteRequest {
  /** @minLength 1 */
  datasetName?: string;
  description?: string;
  /** @minItems 1 */
  items?: PromoteItem[];
}

export type UpdateRunRequestStatus = typeof UpdateRunRequestStatus[keyof typeof UpdateRunRequestStatus];


export const UpdateRunRequestStatus = {
  RUNNING: 'RUNNING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export interface UpdateRunRequest {
  status: UpdateRunRequestStatus;
}

export interface Pageable {
  /** @minimum 0 */
  page?: number;
  /** @minimum 1 */
  size?: number;
  sort?: string[];
}

export interface EvalSummary {
  id?: string;
  evaluatorName?: string;
  score?: number;
  threshold?: number;
  success?: boolean;
  reason?: string;
}

export type ItemSummaryInput = {[key: string]: { [key: string]: unknown }};

export type ItemSummaryExpectedOutput = {[key: string]: { [key: string]: unknown }};

export type ItemSummaryActualOutput = {[key: string]: { [key: string]: unknown }};

export type ItemSummaryMetadata = {[key: string]: { [key: string]: unknown }};

export interface ItemSummary {
  id?: string;
  input?: ItemSummaryInput;
  expectedOutput?: ItemSummaryExpectedOutput;
  actualOutput?: ItemSummaryActualOutput;
  metadata?: ItemSummaryMetadata;
  evalResults?: EvalSummary[];
  createdAt?: string;
  datasetItemId?: string;
  annotation?: AnnotationView;
}

export interface SortObject {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}

export interface PageableObject {
  offset?: number;
  sort?: SortObject;
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  unpaged?: boolean;
}

export interface PageItemSummary {
  totalPages?: number;
  totalElements?: number;
  first?: boolean;
  last?: boolean;
  size?: number;
  content?: ItemSummary[];
  number?: number;
  sort?: SortObject;
  pageable?: PageableObject;
  numberOfElements?: number;
  empty?: boolean;
}

export type RunDetailsStatus = typeof RunDetailsStatus[keyof typeof RunDetailsStatus];


export const RunDetailsStatus = {
  RUNNING: 'RUNNING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export type RunDetailsConfig = {[key: string]: { [key: string]: unknown }};

export interface RunDetails {
  id?: string;
  experimentId?: string;
  experimentName?: string;
  projectName?: string;
  status?: RunDetailsStatus;
  config?: RunDetailsConfig;
  totalItems?: number;
  passedItems?: number;
  passRate?: number;
  startedAt?: string;
  completedAt?: string;
  datasetVersionId?: string;
  datasetVersion?: number;
  items?: PageItemSummary;
}

export interface ProjectSummary {
  id?: string;
  name?: string;
  experimentCount?: number;
  createdAt?: string;
}

export type LatestRunInfoStatus = typeof LatestRunInfoStatus[keyof typeof LatestRunInfoStatus];


export const LatestRunInfoStatus = {
  RUNNING: 'RUNNING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export interface LatestRunInfo {
  runId?: string;
  status?: LatestRunInfoStatus;
  passRate?: number;
  startedAt?: string;
}

export interface ExperimentSummary {
  id?: string;
  name?: string;
  createdAt?: string;
  latestRun?: LatestRunInfo;
}

export interface RunPoint {
  runId?: string;
  startedAt?: string;
  passRate?: number;
  totalItems?: number;
  passedItems?: number;
}

export interface TrendData {
  experimentName?: string;
  projectName?: string;
  runs?: RunPoint[];
}

export type RunSummaryStatus = typeof RunSummaryStatus[keyof typeof RunSummaryStatus];


export const RunSummaryStatus = {
  RUNNING: 'RUNNING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export type RunSummaryConfig = {[key: string]: { [key: string]: unknown }};

export interface RunSummary {
  id?: string;
  status?: RunSummaryStatus;
  config?: RunSummaryConfig;
  itemCount?: number;
  passedCount?: number;
  passRate?: number;
  startedAt?: string;
  completedAt?: string;
  datasetVersionId?: string;
  datasetVersion?: number;
}

export interface EvaluatorDiff {
  name?: string;
  baselineMean?: number;
  candidateMean?: number;
  delta?: number;
  status?: string;
  significant?: boolean;
}

export interface DiffCase {
  datasetItemId?: string;
  index?: string;
  status?: string;
  passFlip?: boolean;
  input?: string;
  evaluators?: EvaluatorDiff[];
}

export interface DiffSummary {
  pairing?: string;
  baselineRunId?: string;
  candidateRunId?: string;
  baselinePassRate?: number;
  candidatePassRate?: number;
  passRateDelta?: number;
  significant?: boolean;
  improvedCount?: number;
  regressedCount?: number;
  unchangedCount?: number;
  addedCount?: number;
  removedCount?: number;
}

export interface PageSort {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}

export interface PageablePage {
  offset?: number;
  sort?: PageSort;
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  unpaged?: boolean;
}

export interface PageResponseDiffCase {
  content?: DiffCase[];
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  empty?: boolean;
  sort?: PageSort;
  pageable?: PageablePage;
}

export interface DiffView {
  summary?: DiffSummary;
  cases?: PageResponseDiffCase;
}

export interface VersionSummary {
  id?: string;
  version?: number;
  description?: string;
  itemCount?: number;
  createdAt?: string;
  createdBy?: string;
}

export interface DatasetDetails {
  id?: string;
  name?: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  versions?: VersionSummary[];
}

export type DatasetItemViewInputs = {[key: string]: { [key: string]: unknown }};

export type DatasetItemViewExpectedOutputs = {[key: string]: { [key: string]: unknown }};

export type DatasetItemViewMetadata = {[key: string]: { [key: string]: unknown }};

export interface DatasetItemView {
  id?: string;
  ordinal?: number;
  inputs?: DatasetItemViewInputs;
  expectedOutputs?: DatasetItemViewExpectedOutputs;
  metadata?: DatasetItemViewMetadata;
}

export interface PageResponseDatasetItemView {
  content?: DatasetItemView[];
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  empty?: boolean;
  sort?: PageSort;
  pageable?: PageablePage;
}

export type AddItems201 = {[key: string]: string};

export type GetRunDetailsParams = {
pageable: Pageable;
};

export type UpdateRun200 = {[key: string]: string};

export type GetTrendsParams = {
limit?: number;
};

export type DiffParams = {
baselineRunId: string;
status?: string;
pageable: Pageable;
};

export type ListItemsParams = {
pageable: Pageable;
};

