/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Key
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  GateRequest,
  GateResult
} from '../generated.schemas';



  
  
  
export const evaluateGate = (
    experimentId: string,
    gateRequest: GateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GateResult>> => {
    return axios.default.post(
      `/api/v1/experiments/${experimentId}/gate`,
      gateRequest,options
    );
  }



export const getEvaluateGateMutationFetcher = (experimentId: string, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: GateRequest }) => {
    return evaluateGate(experimentId, arg, options);
  }
}
export const getEvaluateGateMutationKey = (experimentId: string,) => [`/api/v1/experiments/${experimentId}/gate`] as const;

export type EvaluateGateMutationResult = NonNullable<Awaited<ReturnType<typeof evaluateGate>>>

export const useEvaluateGate = <TError = AxiosError<unknown>>(
  experimentId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof evaluateGate>>, TError, Key, GateRequest, Awaited<ReturnType<typeof evaluateGate>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getEvaluateGateMutationKey(experimentId);
  const swrFn = getEvaluateGateMutationFetcher(experimentId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
