/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  DiffParams,
  DiffView
} from '../generated.schemas';



  
  
  
export const diff = (
    experimentId: string,
    candidateRunId: string,
    params: DiffParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DiffView>> => {
    return axios.default.get(
      `/api/v1/experiments/${experimentId}/runs/${candidateRunId}/diff`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getDiffKey = (experimentId: string,
    candidateRunId: string,
    params: DiffParams,) => [`/api/v1/experiments/${experimentId}/runs/${candidateRunId}/diff`, ...(params ? [params]: [])] as const;

export type DiffQueryResult = NonNullable<Awaited<ReturnType<typeof diff>>>

export const useDiff = <TError = AxiosError<unknown>>(
  experimentId: string,
    candidateRunId: string,
    params: DiffParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof diff>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(experimentId && candidateRunId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getDiffKey(experimentId,candidateRunId,params) : null);
  const swrFn = () => diff(experimentId,candidateRunId,params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
