/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  CreateLlmConnectionRequest,
  LlmConnectionView,
  UpdateLlmConnectionRequest
} from '../generated.schemas';



  
  
  
export const get1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LlmConnectionView>> => {
    return axios.default.get(
      `/api/v1/llm-connections/${id}`,options
    );
  }



export const getGet1Key = (id: string,) => [`/api/v1/llm-connections/${id}`] as const;

export type Get1QueryResult = NonNullable<Awaited<ReturnType<typeof get1>>>

export const useGet1 = <TError = AxiosError<unknown>>(
  id: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof get1>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(id)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGet1Key(id) : null);
  const swrFn = () => get1(id, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const update = (
    id: string,
    updateLlmConnectionRequest: UpdateLlmConnectionRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LlmConnectionView>> => {
    return axios.default.put(
      `/api/v1/llm-connections/${id}`,
      updateLlmConnectionRequest,options
    );
  }



export const getUpdateMutationFetcher = (id: string, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: UpdateLlmConnectionRequest }) => {
    return update(id, arg, options);
  }
}
export const getUpdateMutationKey = (id: string,) => [`/api/v1/llm-connections/${id}`] as const;

export type UpdateMutationResult = NonNullable<Awaited<ReturnType<typeof update>>>

export const useUpdate = <TError = AxiosError<unknown>>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof update>>, TError, Key, UpdateLlmConnectionRequest, Awaited<ReturnType<typeof update>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateMutationKey(id);
  const swrFn = getUpdateMutationFetcher(id, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const delete1 = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.default.delete(
      `/api/v1/llm-connections/${id}`,options
    );
  }



export const getDelete1MutationFetcher = (id: string, options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return delete1(id, options);
  }
}
export const getDelete1MutationKey = (id: string,) => [`/api/v1/llm-connections/${id}`] as const;

export type Delete1MutationResult = NonNullable<Awaited<ReturnType<typeof delete1>>>

export const useDelete1 = <TError = AxiosError<unknown>>(
  id: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof delete1>>, TError, Key, Arguments, Awaited<ReturnType<typeof delete1>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDelete1MutationKey(id);
  const swrFn = getDelete1MutationFetcher(id, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const list1 = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LlmConnectionView[]>> => {
    return axios.default.get(
      `/api/v1/llm-connections`,options
    );
  }



export const getList1Key = () => [`/api/v1/llm-connections`] as const;

export type List1QueryResult = NonNullable<Awaited<ReturnType<typeof list1>>>

export const useList1 = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof list1>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getList1Key() : null);
  const swrFn = () => list1(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const create = (
    createLlmConnectionRequest: CreateLlmConnectionRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LlmConnectionView>> => {
    return axios.default.post(
      `/api/v1/llm-connections`,
      createLlmConnectionRequest,options
    );
  }



export const getCreateMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: CreateLlmConnectionRequest }) => {
    return create(arg, options);
  }
}
export const getCreateMutationKey = () => [`/api/v1/llm-connections`] as const;

export type CreateMutationResult = NonNullable<Awaited<ReturnType<typeof create>>>

export const useCreate = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof create>>, TError, Key, CreateLlmConnectionRequest, Awaited<ReturnType<typeof create>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateMutationKey();
  const swrFn = getCreateMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
