/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  AlertWebhookView,
  CreateAlertWebhookRequest,
  UpdateAlertWebhookRequest
} from '../generated.schemas';



  
  
  
export const getAlertWebhook = (
    projectId: string,
    webhookId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlertWebhookView>> => {
    return axios.default.get(
      `/api/v1/projects/${projectId}/alert-webhooks/${webhookId}`,options
    );
  }



export const getGetAlertWebhookKey = (projectId: string,
    webhookId: string,) => [`/api/v1/projects/${projectId}/alert-webhooks/${webhookId}`] as const;

export type GetAlertWebhookQueryResult = NonNullable<Awaited<ReturnType<typeof getAlertWebhook>>>

export const useGetAlertWebhook = <TError = AxiosError<unknown>>(
  projectId: string,
    webhookId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAlertWebhook>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(projectId && webhookId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAlertWebhookKey(projectId,webhookId) : null);
  const swrFn = () => getAlertWebhook(projectId,webhookId, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const updateAlertWebhook = (
    projectId: string,
    webhookId: string,
    updateAlertWebhookRequest: UpdateAlertWebhookRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlertWebhookView>> => {
    return axios.default.put(
      `/api/v1/projects/${projectId}/alert-webhooks/${webhookId}`,
      updateAlertWebhookRequest,options
    );
  }



export const getUpdateAlertWebhookMutationFetcher = (projectId: string,
    webhookId: string, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: UpdateAlertWebhookRequest }) => {
    return updateAlertWebhook(projectId, webhookId, arg, options);
  }
}
export const getUpdateAlertWebhookMutationKey = (projectId: string,
    webhookId: string,) => [`/api/v1/projects/${projectId}/alert-webhooks/${webhookId}`] as const;

export type UpdateAlertWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof updateAlertWebhook>>>

export const useUpdateAlertWebhook = <TError = AxiosError<unknown>>(
  projectId: string,
    webhookId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateAlertWebhook>>, TError, Key, UpdateAlertWebhookRequest, Awaited<ReturnType<typeof updateAlertWebhook>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateAlertWebhookMutationKey(projectId,webhookId);
  const swrFn = getUpdateAlertWebhookMutationFetcher(projectId,webhookId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const deleteAlertWebhook = (
    projectId: string,
    webhookId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.default.delete(
      `/api/v1/projects/${projectId}/alert-webhooks/${webhookId}`,options
    );
  }



export const getDeleteAlertWebhookMutationFetcher = (projectId: string,
    webhookId: string, options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteAlertWebhook(projectId, webhookId, options);
  }
}
export const getDeleteAlertWebhookMutationKey = (projectId: string,
    webhookId: string,) => [`/api/v1/projects/${projectId}/alert-webhooks/${webhookId}`] as const;

export type DeleteAlertWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAlertWebhook>>>

export const useDeleteAlertWebhook = <TError = AxiosError<unknown>>(
  projectId: string,
    webhookId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteAlertWebhook>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteAlertWebhook>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteAlertWebhookMutationKey(projectId,webhookId);
  const swrFn = getDeleteAlertWebhookMutationFetcher(projectId,webhookId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const listAlertWebhooks = (
    projectId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlertWebhookView[]>> => {
    return axios.default.get(
      `/api/v1/projects/${projectId}/alert-webhooks`,options
    );
  }



export const getListAlertWebhooksKey = (projectId: string,) => [`/api/v1/projects/${projectId}/alert-webhooks`] as const;

export type ListAlertWebhooksQueryResult = NonNullable<Awaited<ReturnType<typeof listAlertWebhooks>>>

export const useListAlertWebhooks = <TError = AxiosError<unknown>>(
  projectId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listAlertWebhooks>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(projectId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListAlertWebhooksKey(projectId) : null);
  const swrFn = () => listAlertWebhooks(projectId, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const createAlertWebhook = (
    projectId: string,
    createAlertWebhookRequest: CreateAlertWebhookRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlertWebhookView>> => {
    return axios.default.post(
      `/api/v1/projects/${projectId}/alert-webhooks`,
      createAlertWebhookRequest,options
    );
  }



export const getCreateAlertWebhookMutationFetcher = (projectId: string, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: CreateAlertWebhookRequest }) => {
    return createAlertWebhook(projectId, arg, options);
  }
}
export const getCreateAlertWebhookMutationKey = (projectId: string,) => [`/api/v1/projects/${projectId}/alert-webhooks`] as const;

export type CreateAlertWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof createAlertWebhook>>>

export const useCreateAlertWebhook = <TError = AxiosError<unknown>>(
  projectId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createAlertWebhook>>, TError, Key, CreateAlertWebhookRequest, Awaited<ReturnType<typeof createAlertWebhook>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateAlertWebhookMutationKey(projectId);
  const swrFn = getCreateAlertWebhookMutationFetcher(projectId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
