/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  AlignmentView
} from '../generated.schemas';



  
  
  
export const alignment = (
    runId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AlignmentView>> => {
    return axios.default.get(
      `/api/v1/runs/${runId}/alignment`,options
    );
  }



export const getAlignmentKey = (runId: string,) => [`/api/v1/runs/${runId}/alignment`] as const;

export type AlignmentQueryResult = NonNullable<Awaited<ReturnType<typeof alignment>>>

export const useAlignment = <TError = AxiosError<unknown>>(
  runId: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof alignment>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(runId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getAlignmentKey(runId) : null);
  const swrFn = () => alignment(runId, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
