/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  CreateRunRequest,
  CreateRunResponse,
  ExperimentSummary,
  ProjectSummary
} from '../generated.schemas';



  
  
  
export const createRun = (
    projectName: string,
    createRunRequest: CreateRunRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateRunResponse>> => {
    return axios.default.post(
      `/api/v1/projects/${projectName}/runs`,
      createRunRequest,options
    );
  }



export const getCreateRunMutationFetcher = (projectName: string, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: CreateRunRequest }) => {
    return createRun(projectName, arg, options);
  }
}
export const getCreateRunMutationKey = (projectName: string,) => [`/api/v1/projects/${projectName}/runs`] as const;

export type CreateRunMutationResult = NonNullable<Awaited<ReturnType<typeof createRun>>>

export const useCreateRun = <TError = AxiosError<unknown>>(
  projectName: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createRun>>, TError, Key, CreateRunRequest, Awaited<ReturnType<typeof createRun>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateRunMutationKey(projectName);
  const swrFn = getCreateRunMutationFetcher(projectName, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const listProjects = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProjectSummary[]>> => {
    return axios.default.get(
      `/api/v1/projects`,options
    );
  }



export const getListProjectsKey = () => [`/api/v1/projects`] as const;

export type ListProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof listProjects>>>

export const useListProjects = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listProjects>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListProjectsKey() : null);
  const swrFn = () => listProjects(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const listExperiments = (
    projectName: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ExperimentSummary[]>> => {
    return axios.default.get(
      `/api/v1/projects/${projectName}/experiments`,options
    );
  }



export const getListExperimentsKey = (projectName: string,) => [`/api/v1/projects/${projectName}/experiments`] as const;

export type ListExperimentsQueryResult = NonNullable<Awaited<ReturnType<typeof listExperiments>>>

export const useListExperiments = <TError = AxiosError<unknown>>(
  projectName: string, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof listExperiments>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(projectName)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getListExperimentsKey(projectName) : null);
  const swrFn = () => listExperiments(projectName, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export const deleteProject = (
    projectName: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.default.delete(
      `/api/v1/projects/${projectName}`,options
    );
  }



export const getDeleteProjectMutationFetcher = (projectName: string, options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteProject(projectName, options);
  }
}
export const getDeleteProjectMutationKey = (projectName: string,) => [`/api/v1/projects/${projectName}`] as const;

export type DeleteProjectMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProject>>>

export const useDeleteProject = <TError = AxiosError<unknown>>(
  projectName: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteProject>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteProject>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteProjectMutationKey(projectName);
  const swrFn = getDeleteProjectMutationFetcher(projectName, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
