/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  List2Params,
  PageReviewQueueItem
} from '../generated.schemas';



  
  
  
export const list2 = (
    params: List2Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PageReviewQueueItem>> => {
    return axios.default.get(
      `/api/v1/review-queue`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getList2Key = (params: List2Params,) => [`/api/v1/review-queue`, ...(params ? [params]: [])] as const;

export type List2QueryResult = NonNullable<Awaited<ReturnType<typeof list2>>>

export const useList2 = <TError = AxiosError<unknown>>(
  params: List2Params, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof list2>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getList2Key(params) : null);
  const swrFn = () => list2(params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
